-- AlterTable
ALTER TABLE `post` ADD COLUMN `createBy` VARCHAR(191) NOT NULL DEFAULT 'admin',
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updateBy` VARCHAR(191) NOT NULL DEFAULT 'admin',
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` ADD COLUMN `createBy` VARCHAR(191) NOT NULL DEFAULT 'admin',
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updateBy` VARCHAR(191) NOT NULL DEFAULT 'admin',
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
